name: ci

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      PYTHONPATH: .
      PYTHONUNBUFFERED: '1'
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
      PIP_NO_PYTHON_VERSION_WARNING: '1'

    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.11']  # add '3.12' later if you want

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install --prefer-binary -r requirements.txt

      - name: Run tests
        run: |
          pytest -q tests --maxfail=1 -ra --durations=10 --junitxml=pytest.xml

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report-${{ matrix.python-version }}
          path: pytest.xml
          if-no-files-found: ignore
          retention-days: 7
